# Generated by Django 3.0.7 on 2020-06-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='One',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('head', models.CharField(max_length=25)),
                ('backimg', models.ImageField(blank=True, null=True, upload_to='backimg')),
                ('profimg', models.ImageField(blank=True, null=True, upload_to='profimg')),
            ],
        ),
    ]
