# Generated by Django 3.0.7 on 2020-07-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='one',
            name='head',
            field=models.CharField(max_length=200),
        ),
    ]
