# Generated by Django 3.0.7 on 2020-07-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_auto_20200701_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('job_desc', models.TextField()),
            ],
        ),
    ]
