# Generated by Django 3.0.7 on 2020-07-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0003_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('features', models.CharField(max_length=20)),
                ('features_desc', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
    ]
