# Generated by Django 3.0.7 on 2020-07-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0007_two_explaination_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='two_explaination',
            name='features_desc',
            field=models.CharField(max_length=250),
        ),
    ]
